# Generated by Django 4.0.4 on 2022-05-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "message",
                    models.CharField(max_length=512, primary_key=True, serialize=False),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("0", "Trace"),
                            ("1", "Debug"),
                            ("2", "Info"),
                            ("3", "Warning"),
                            ("4", "Critical"),
                            ("5", "Fatal"),
                        ],
                        default="0",
                        max_length=2,
                    ),
                ),
                ("detail", models.TextField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("count", models.IntegerField(default=0)),
                ("traceback", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
